### ISSUE TITLE
WatchOS Support

### ISSUE THREAD

**Issue by Ketan-Simform** [mapbox/mapbox-maps-ios#1008]
## WatchOS support

I need to use map with poly lines in WatchOS. I tried with rest APIs and Mapbox static SDK but due to large data it fails. I have already seen one application [WatchSmith](https://apps.apple.com/us/app/watchsmith/id1483088503). Is there any solutions or private repo there for similar implementation. 

@mapbox

**Comment by ZiZasaurus** [comment]
@Ketan-Simform, when you say "due to large data it fails", can you let me know what is failing?

**Comment by Ketan-Simform** [comment]
@ZiZasaurus I am facing an error when I have large amount of data while adding map poly lines. With below error:
Error Domain=MBStaticErrorDomain Code=-1 "server error" UserInfo={NSLocalizedFailureReason=server error}

and another issue is if I try to add more than 100 overlays it crashes with assert.

**Comment by ZiZasaurus** [comment]
@Ketan-Simform, thank you for this additional information. Please note that there is a restriction on the number of features in a GeoJSON overlay, as well as a restriction on the length of the string encoding of all the overlays combined:

> Overlays cannot consist of more than 100 features. The maximum overlay length is 2083 characters.

A Path’s [string-encoded ](https://github.com/mapbox/MapboxStatic.swift/blob/a880e932c1d62562d260745a7b4200ab7e63cc74/MapboxStatic/Overlay.swift#L388-L396) length depends on the [Polyline encoding](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) of all the coordinates, plus any styling options.

As Maps SDK cannot be used with WatchOS because Metal API is not available on watchOS, the Mapbox Static API would be the best way to display maps on the Apple Watch, however, you may need to adjust the size of your static image to ensure that it can be displayed on watchOS.

**Comment by Ketan-Simform** [comment]
Okay, Thank you for your response @ZiZasaurus. 

So as per my requirement Mapbox Static won't work for me. So do you think there is any way I can add more than 100 features on overlay? 
Using turf.js SDK or any other mapbox SDK which supports WatchOS.

**Comment by ZiZasaurus** [comment]
You can continue to use MapboxStatic.swift, however, there is a limit to the length of the URL, which is easy to hit when adding GeoJSON to the image. You can greatly reduce the size of any LineString using the Path overlay instead of GeoJSON. If that isn’t enough, you can also use Turf to simplify the line.

**Comment by ZiZasaurus** [comment]
@Ketan-Simform closing this issue but please feel free to reopen if you have additional questions.

**Comment by Hitarthbhatt** [comment]
Hey @ZiZasaurus, can't we use mapbox iOS map in watchOS instead of static images because I had seen an watchOS app which uses fully functional mapbox map just like iOS.
If you want to I can also share the link of the application for a proof.

**Comment by ZiZasaurus** [comment]
@Hitarthbhatt can you please share the app you're referring to?

**Comment by Ketan-Simform** [comment]
> @Hitarthbhatt can you please share the app you're referring to?

Hey @ZiZasaurus We also tried using overlays instead of GeoJSON still I am hitting the size limit. I have seen WatchSmith (https://apps.apple.com/us/app/watchsmith/id1483088503) you can check that out. We also tried line simplification but that costs us with data accuracy so is there any way I can get it done like the WatchSmith application. 

Thank you.
