### ISSUE TITLE
MapboxMap not deallocated

### ISSUE THREAD

**Issue by Eke** [mapbox/mapbox-maps-ios#1119]
## Environment

- Xcode version: 13.2
- iOS version: 15.3
- Devices affected: iPhone XS real device
- Maps SDK Version:  v10.3.0

## Observed behavior and steps to reproduce

`MapboxMap` is retained in memory if you try to dismiss / replace UIViewController while map has some ongoing animations.

## Expected behavior

`MapboxMap` is not retained in memory and it's `deinit` method is called.

## Notes / preliminary analysis

I was able to fix this problem by calling `_mapView.camera.cancelAnimations()` in view models `deinit` function.

**Comment by macdrevx** [comment]
Some progress: I can reproduce this only with the deceleration animation after a pan gesture. This happens due to the following cycle:

`CameraAnimationsManager --> GestureDecelerationCameraAnimator --> locationChangeHandler --> PanGestureHandler --> CameraAnimationsManager`

A similar cycle exists if you swap in `completion` for `locationChangeHandler`.

**Comment by macdrevx** [comment]
Similar cycles seem possible with `DoubleTouchToZoomOutGestureHandler`, `DoubleTapToZoomInGestureHandler`

**Comment by macdrevx** [comment]
Seems like the general pattern is…

`CameraAnimationsManager --(internalAnimator/runningCameraAnimators)--> CameraAnimator --(some closure)--> ... --> CameraAnimationsManager`

where the ... could be CameraAnimationsManager directly or some other series of strong references that leads to it like `MapView --> CameraAnimationsManager` or `GestureHandler --> CameraAnimationsManager`.

As long as the `CameraAnimator` in this cycle invokes its completion block, the cycle will be broken (All `CameraAnimator` implementations release their completion blocks after invoking them, `CameraAnimationsManager` clears its `internalAnimator` reference when ease-to and fly-to completion blocks are invoked, and removes animators from `runningCameraAnimators` when they complete), but under certain circumstances, the completion blocks might not be invoked:

* If the MapView is removed from its window, it invalidates its display link and `FlyToCameraAnimator` and `GestureDecelerationCameraAnimator` will not receive any more `update()` invocations and will not invoke their completion blocks.
* If `MapView` is deinited without being removed from its window (e.g. the entire window is deinited along with all of its descendant views), the animators will not receive any more `update()` invocations and will not invoke their completion blocks. This scenario is almost certainly less common, but should still be handled.

`BasicCameraAnimator` (and, by extension, ease-to) seems to be immune to these conditions since the underlying `UIViewPropertyAnimator` invokes its completion blocks in either case.

Possible solutions:

* Clear `CameraAnimationsManager.internalAnimator` and `.runningCameraAnimators` when `MapView` is deinited and when `MapView` is removed from its window (in case `MapView` is involved in the cycle). Prevent `.internalAnimator` and `.runningCameraAnimators` from being set when `MapView` does not have a display link.
* Update internal usage to only capture weak references to `CameraAnimationsManager` in animator completion blocks and update documentation to advise developers to do the same in their apps.

I like the first solution better because it would make the API less error-prone.

**Comment by Eke** [comment]
@macdrevx I can confirm that it was happening only with the deceleration animation after a pan gesture in my case.
