### ISSUE TITLE
AnyTouchGestureRecognizer.canBePrevented prevents single tap gestures in Flutter environment

### ISSUE THREAD

**Issue by landyrev** [mapbox/mapbox-maps-ios#1194]
## Environment

- Xcode version: 13.3
- iOS version: 15.4
- Devices affected: any iPhone
- Maps SDK Version: 10.3.0
- Flutter SDK version: 2.8.1

## Observed behavior and steps to reproduce
We use Mapbox SDK as a native module (integrated [this way](https://docs.flutter.dev/development/platform-integration/platform-views#on-the-platform-side-1))

After upgrading from 10.2.0 to 10.3.0 we got our single tap gestures stopped working after a single tap. (see a screencast with demonstration: https://cln.sh/9SNfJv). Steps to reproduce are:
1. Run Mapbox in a flutter environment (with any style)
2. Tap on map — single tap gesture fired
3. Tap on map again — single tap gesture not fired
4. Drag map — map not dragged, pan gesture not fired
5. Drag again — map dragged, pan gesture fired
6. Tap on map — single tap gesture fired

## Expected behavior

Single tap gestures works on every tap

## Notes / preliminary analysis

I've found out that if I remove `AnyTouchGestureRecognizer.canBePrevented` override (or make it returns true) the problem disappears

**Comment by landyrev** [comment]
minimal reproducible test case: https://github.com/landyrev/mapbox_flutter

**Comment by macdrevx** [comment]
Thanks for the test case @landyrev. Using it, I'm able to reproduce the issue you describe.

AnyTouchGestureRecognizer is used to disable camera animations while there are touches on the map so that you can "grab" the map to stop it if it's animating. The change between 10.2 and 10.3 that seems to result in this behavior is that it doesn't transition into the `began` state until after a short delay (previously it did so immediately). [This change](https://github.com/mapbox/mapbox-maps-ios/pull/1058) was made so that repeated use of double tap or double touch gestures would be smooth since the animations are not interrupted in between each gesture.

I haven't fully identified the root cause of why this delay breaks Flutter yet, but some initial research yields a few bits of info that might be of interest:

[UiKitView docs](https://api.flutter.dev/flutter/widgets/UiKitView-class.html) indicate that "Embedding UIViews is still preview-quality". There are also known issues with flutter iOS platform views:

- https://github.com/flutter/flutter/issues/37579
- https://github.com/flutter/flutter/issues/61991
- https://docs.google.com/document/d/1268wVunG_7Y4eOyKBZxFmi9raB0idZwoPfT3inZsh7k/edit

I recommend reaching out to the Flutter folks to see whether they have any advice about this situation.

cc: @pengdev @yunikkk FYI

**Comment by macdrevx** [comment]
One other note — the workaround you identified (returning true from `canBePrevented`) breaks other map behaviors (e.g. if there's an animation, and you start panning, the animation continues in parallel, which doesn't look right). `canBePrevented` itself was unchanged from 10.2 to 10.3. My guess is that returning true just means that the AnyTouchGestureRecognizer is being ignored.

**Comment by landyrev** [comment]
> @landyrev possible good news here — it seems like setting the gesture recognizer state to .failed when all touches end before the delay may resolve this issue. I created a PR for this here: #1210. Can you try it out and see whether it resolves this issue for you?

Hi @macdrevx! https://github.com/mapbox/mapbox-maps-ios/pull/1210 did the trick great catch, thank you!
