### ISSUE TITLE
Unusual CPU usage on idle

### ISSUE THREAD

**Issue by kushsolitary** [mapbox/mapbox-maps-ios#1384]
## Environment

- Xcode version: 13.4.1
- iOS version: 15.4.1
- Devices affected: iPhone 11 Pro
- Maps SDK Version: 10.4.3

## Observed behavior and steps to reproduce

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/650476/173175161-38040b8c-e2c1-4ca8-9e66-860a7927fded.png">

As you can see, the `updateHeadingOrientationIfNeeded()` is being called every second or so, which causes spikes in the CPU usage and energy usage. 

Is there a way to stop this from happening?

**Comment by kushsolitary** [comment]
> @kushsolitary are you only experiencing this behavior when the location / heading are being displayed?

I am seeing this without accessing the location/displaying the heading of the user.

**Comment by samskinner32** [comment]
We are also seeing uncomfortably high CPU usage when we have the user puck enabled.

With this line added to our code: `map.location.options.puckType = .puck2D()`, we sit at 30-40% CPU, but if I leave that line out I'm sitting at 0-4% CPU.

Any way to address this? We're having to disable the puck for now because it's so high

**Comment by OdNairy** [comment]
The original issue was addressed by limiting the frequency of heading updates impacting the rendering engine. We also planning some following improvements to optimize it further.
The puck location usage issue is tracked in https://github.com/mapbox/mapbox-maps-ios/issues/1939#issuecomment-1594398407
