### ISSUE TITLE
In 2D and 3D, user location puck is hidden by PointAnnotations

### ISSUE THREAD

**Issue by johnkassebaum** [mapbox/mapbox-maps-ios#142]
## Environment

- Xcode version: 12.4
- iOS version: 14.4
- Devices affected: any
- Maps SDK Version: beta.13

## Observed behavior and steps to reproduce

Add a `PointAnnotation` at a location, then physically have the device near that location but not exactly coincident.

When zoomed out, the user location puck is not drawn.
![goOHy](https://user-images.githubusercontent.com/39099029/109077251-af29b580-76b0-11eb-875b-b150c4f8b930.png)

When zoomed in to a point that the location puck appears, pitch the map and pinch to rotate the map 360 degrees about the `PointAnnotation` and the user location puck, and the `PointAnnotation` will always appear in front of the user location puck, which is not possible because there exists 180 degrees where the puck is closer to the camera than the annotation.
![WcLOc](https://user-images.githubusercontent.com/39099029/109077276-b94bb400-76b0-11eb-8b38-f06d56094aed.png)
![UwPjG](https://user-images.githubusercontent.com/39099029/109077303-c23c8580-76b0-11eb-8bfe-b682b66de95d.png)
![gIi9k](https://user-images.githubusercontent.com/39099029/109077322-c9639380-76b0-11eb-9dac-7bf2622c7f44.png)
![BYSJH](https://user-images.githubusercontent.com/39099029/109077341-d1bbce80-76b0-11eb-8666-64f18f7407f6.png)

## Expected behavior

In Mapbox SDK versions before v10, the puck  always appears on top of annotations.
The user location puck should not be included in clustering.

**Comment by neelmistry94** [comment]
@johnkassebaum This issue is now fixed. The new default behavior is such that the Location Puck will sit above the Point Annotation. 

We have also created a `LayerPosition` enum that will allow you to easily place layers, above, or below another Layer. Please see [this](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/LayerPositionExample.swift) example that will highlight different ways you can do this. 

Feel free to close the issue if it has been resolved after reading this comment.

**Comment by neelmistry94** [comment]
@johnkassebaum I will be closing out this ticket, please reach out for further assistance.
