### ISSUE TITLE
Allow mapboxMap.point() to Return for Out of Bounds Coordinates

### ISSUE THREAD

**Issue by Joseph-Sam** [mapbox/mapbox-maps-ios#1886]
## New Feature
Enable mapboxMap.point(for: CLLocationCoordinate2D) to return out of bounds values instead of defaulting to -1 when the point is off screen.

## Why
In Pre V10 versions of Mapbox the function `mapView.convert(inputCoord, toPointTo: mapView).x` allowed for determining where offscreen annotations were. This allowed me to show custom buttons at the edges of the map that would more around when scrolling to always be at the closest XY to where the offscreen annotation was. 
However, the current implementation of mapboxMap.point(for: CLLocationCoordinate2D) always returns -1 when the value out of bounds. This is preventing me from completing my migration to V10.

**Comment by baleboy** [comment]
@Joseph-Sam thanks for the report. Unfortunately this was an intentional limitation because of the inaccuracies that we had when the users were able to query the points outside of the map’s bounds. You can see a thread about it [here](https://github.com/mapbox/mapbox-maps-ios/issues/788) with more details and an incomplete sample implementation, in case you want to give this a try.

**Comment by Joseph-Sam** [comment]
Thank you for the quick response!
Are these inaccuracies new to V10? Everything worked fine (for my usage) in prior versions.

I will give the implementation linked a try but made something very similar in V10 using N, S, E, W bounds that proved to have its own issues, mostly with crossing the anti-meridian.
