### ISSUE TITLE
Symbol vs Circle layer with View Annotations

### ISSUE THREAD

**Issue by SzymonMatysik** [mapbox/mapbox-maps-ios#1952]
Hey, 

I've been using MapBox since 2019 and great thanks for your work.

I got one simple question, what is a difference between symbol and circle layer that causes circle layer to do not render view annotations associated with feature id?

I'm using example project, the ViewAnnotationMarkerExample, in line 127, I've changed Symbol layer into circle layer:
```
        //var layer = SymbolLayer(id: Constants.LAYER_ID)
        //layer.source = Constants.SOURCE_ID
        //layer.iconImage = .constant(.name(Constants.BLUE_ICON_ID))
        //try? mapView.mapboxMap.style.addLayer(layer)

        var layer = CircleLayer(id: Constants.LAYER_ID)
        layer.source = Constants.SOURCE_ID
        try? mapView.mapboxMap.style.addLayer(layer)
```
Circles are more convenient over Symbols to our use cases as they can be modified easily during runtime to different color/size etc.

**Comment by baleboy** [comment]
First of all, thanks for the kind words!

Currently, a ViewAnnotation can be pinned only to a symbol layer. Pinning is done so that if symbol layer's symbol will disappear (for any reason, most likely collision with some other symbol), the associated view annotation will disappear as well. Circle layers however don't support collisions, so there is little point in pinning the view annotations to them.

If you are associating the annotation with the circle layer so that they have the same position, you can simply draw the annotation at the same coordinates as the circle.

Hope this helps!
