### ISSUE TITLE
 Value of type 'MGLOfflinePack' has no member 'setContext'

### ISSUE THREAD

**Issue by OffsureDev** [mapbox/mapbox-maps-ios#1955]
## Environment

Xcode version: 14.2
iOS version: iOS 16.4.1
Devices affected: All iOS devices
Maps SDK Version:
  - Mapbox-iOS-SDK (5.5.1)
  - MapboxCommon (22.1.0)
  - MapboxCoreMaps (10.7.0):
    - MapboxCommon (~> 22.1)
  - MapboxGeocoder.swift (0.14.0)
  - MapboxMaps (10.7.0):
    - MapboxCommon (= 22.1.0)
    - MapboxCoreMaps (= 10.7.0)
    - MapboxMobileEvents (= 1.0.8)
    - Turf (~> 2.0)
  - MapboxMobileEvents (1.0.8)
  
  ## Installed Pod 
  
   pod 'AerisWeather/Mapbox'
  pod 'MapboxMaps'
  pod 'MapboxGeocoder.swift'
  
  I had implemented the offline map and I want to set the MGLOfflinePack context but I'm getting the following issue :- 
 
 `Value of type 'MGLOfflinePack' has no member 'setContext'` 
 
 ### Code sample
![Screenshot 2023-05-02 at 5 19 25 PM](https://user-images.githubusercontent.com/132354035/235658167-81d1b21c-61c8-4938-80df-e9cdc0c46df8.png)

**Comment by pjleonard37** [comment]
Hi @OffsureDev -- 

This issue is likely related to pulling in two Mapbox Maps iOS SDK versions: Mapbox-iOS-SDK (5.5.1) and MapboxMaps (10.7.0). Mapbox-iOS-SDK is an old version of the SDK that should be removed fully from your project. Please refer to [this guide](https://docs.mapbox.com/ios/maps/guides/migrate-to-v10/) if you need assistance migrating your project fully from version Mapbox-iOS-SDK (5.5.1) to our v10 major version. For Offline guidance please see [this guide](https://docs.mapbox.com/ios/maps/guides/offline/).
