### ISSUE TITLE
Use symbol lyaer to show dynamic content

### ISSUE THREAD

**Issue by abouroubi** [mapbox/mapbox-maps-ios#2023]
I'm trying to show icons on the map using the Symbol Layer, but those icons need to have dynamic text in them.
And this text comes from a property in the GeoJSON data source.

Is there a way to do it ?

Here is the example image
![image](https://github.com/mapbox/mapbox-maps-ios/assets/11291350/f074b874-d7ff-42fb-9c84-a909cb2aee76)

**Comment by maios** [comment]
Hi @abouroubi 
Thanks for writing in. This can be done using [Style Expression](https://docs.mapbox.com/style-spec/reference/expressions/) since we support Expressions for [SymbolLayer/textField](https://docs.mapbox.com/ios/maps/api/10.6.1/Structs/SymbolLayer.html#/s:10MapboxMaps11SymbolLayerV9textFieldAA5ValueOySSGSgvp). You can find multiple example usages in our Examples app, for example [PointClusteringExample.swift#L109](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/PointClusteringExample.swift#L109)

For questions like this about how to use particular features of the Mapbox Maps SDK, including [Work with Expressions](https://docs.mapbox.com/ios/maps/guides/styles/use-expressions/), please take advantage of the Support Resources on our website. You can find them [here](https://www.mapbox.com/support). If you have a specific question you can ask on the [Mapbox Developer Discord](https://docs.mapbox.com/help/getting-started/mapbox-developer-discord/) or submit a technical support request via a form [here](https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231). For more in-depth support with using Mapbox products we recommend subscribing to a Support Plan. You can learn more about what is offered on each plan [here](https://www.mapbox.com/support).
