### ISSUE TITLE
SwiftUI MapView Consume Lots of energy

### ISSUE THREAD

**Issue by Re-Core** [mapbox/mapbox-maps-ios#2051]
## Environment

- Xcode version:
- iOS version:15.0
- Devices affected: Iphone 13 pro max
- Maps SDK Version: 11.0.0 rc1

## Observed behavior and steps to reproduce
While running the application i get a very high energy impact, i am using the SwiftUI Mapbox MapVIew version.

I do show my current user using Puck3D but i do not show any pulse effect, i tried with 2D Puck and i had the same issue.
On My map i do have PointAnnotationGroup with many Annotation around the user.

i tried using other SwiftUI Map like apple Map And Google Map and i didn't face that issue.

while my application is in foreground the energy impact is VERY HIGH. and the reason is that when i show the Map my GPU is always around %30 - %45, which is way higher than its supposed too. 

This high CPU Usage leads to a very high device Temperature which leads to throttling and unusable apps.

`@ViewBuilder private var content: some View {
        
        MapReader { proxy in
            Map(viewport: $viewPort, content: {
                if isTrafficLayerInitilized {
                    
                    PointAnnotationGroup(reportViewModel.reports) { report in
                        PointAnnotation(coordinate: report.coordinate)
                            .image(annotationImage(report: report, isLowZoom: usePointAnnotationOnLowZoom))
                            .iconAnchor(.bottom)
                            .iconSize(0.7)
                            .iconOffset([0.0, 8.0])
                    }
                    
                    if let report = reportViewModel.reportOfCurrentRegion, reportViewModel.alertUser {
                        ViewAnnotation(report.coordinate, anchor: .center) {
                            CircleAlertPulsAnnotationView(reportType: report.reportType)
                        }
                    }
                    
                    createPuck3D()
                }
            })
            .onCameraChanged(action: { camera in
                usePointAnnotationOnLowZoom = camera.cameraState.zoom < 11.5
            })
            .mapStyle(.standard(lightPreset: .dawn))
            .ornamentOptions(configureOrnamentOptions())
            .onStyleLoaded(action: { _ in
                proxy.map.map { initStyleLayer($0) }
                configureMap()
            })
            .gesture(
                DragGesture()
                    .onChanged { _ in
                        guageState = .idle
                    }
            )
            
        }
    }`

![Screenshot 2023-11-08 at 3 12 40 PM](https://github.com/mapbox/mapbox-maps-ios/assets/40316130/e972a30a-8714-4ec4-ae77-0642c79dcfde)

I believe the issue is within how Mapbox handles showing Annotation on the map, as we know in swiftUI when any Changes happen on the UI that View is being rendered. what i believe is happening here is that as my user is changing Location those annotation are being redrawn on the screen which leads to the high GPU usage.

The reason for this and my evidence are is when i do remove the PointAnnotation and the things that goes on top of the map my energy usage drops exponentially as you can see in the down below image.

![Screenshot 2023-11-08 at 3 27 22 PM](https://github.com/mapbox/mapbox-maps-ios/assets/40316130/4a6fefed-2be2-40bd-a286-f5deabcf1adf)

**Comment by persidskiy** [comment]
Hi @Re-Core , thank you for the feedback!  I see two possible reasons for the high CPU consumption. 

First is SwiftUI-related. The `onCameraChanged` subscription that you have will lead to `body` re-execution of your SwiftUI view on every rendering frame, even if the zoom hans't changed.
```swift
.onCameraChanged(action: { camera in
    usePointAnnotationOnLowZoom = camera.cameraState.zoom < 11.5
})
```
This happens because SwiftUI re-executes the body on every rendering frame when it sees that any `@State` is updated, even if it's value is Bool, and not changed. In the code above you update `usePointAnnotationOnLowZoom` (which I suppose is a `@State`) on every camera change (which happens at 60 fps).
Check out the [onCameraChanged doc](https://docs.mapbox.com/ios/maps/api/11.0.0-rc.1-docc/documentation/mapboxmaps/map-swift.struct/oncamerachanged(action:)) to learn how to fix it. Besides that, the SwiftUI `Map` should consume CPU comparable to the UIKit `MapView`.

The second reason is the high-frequency puck updates. Especially, if you use `.followPuck` viewport. The 3D puck is known to consume more CPU than 2D puck. The most optimal is 2D Puck without pulsing and bearing. You can play with different puck types and see if there is any change. Try just a `Puck2D()`, would you observe the same results?

**Comment by persidskiy** [comment]
Hi @Re-Core did you try any suggestions, were they helpful?
