### ISSUE TITLE
MapboxCommon crashes randomly

### ISSUE THREAD

**Issue by fawzirifai** [mapbox/mapbox-maps-ios#2080]
## Environment

- Xcode version: Xcode 15.1
- iOS version: 15.7.5 and 16.6.1
- Devices affected: iPhone 8 and iPhone 7 Plus
- Maps SDK Version: 11.0.0

## Observed behavior and steps to reproduce

Here are 2 crash reports:
[Archive.zip](https://github.com/mapbox/mapbox-maps-ios/files/13711909/Archive.zip)

## Expected behavior

The app should not crash at all.

## Notes / preliminary analysis

I think the crash happens when switching from background to foreground.

**Comment by pjleonard37** [comment]
Hi @fawzirifai - 

Thanks for reporting. Have you been able to reproduce this issue locally? If so, can you share a project which does so?

**Comment by fawzirifai** [comment]
Unfortunately, I couldn't reproduce it.

**Comment by fawzirifai** [comment]
It appears that the app crashes after being in the background for an extended period, such as an hour or more. This crash occurs while the app is still running in the background, and a crash notification from TestFlight is displayed on the screen. @pjleonard37

**Comment by pjleonard37** [comment]
Hi @fawzirifai  -- 

Thanks for sharing these additional details. It looks like more information is needed to identify the root cause of the issue you are seeing. To more easily share this info, please reach out to our Support team using the contact form linked at the bottom of [this page](https://www.mapbox.com/support). Their resources can assist you in diagnosing the problem. 

As your investigation will continue there I'm going to close out this issue.

**Comment by OdNairy** [comment]
> failed to terminate gracefully after 5.0s

@fawzirifai it seems there is some hang when system trying to terminate the app
