### ISSUE TITLE
SwiftUI onMapTapGesture high latency

### ISSUE THREAD

**Issue by Tapestes** [mapbox/mapbox-maps-ios#2112]
## Environment

- Xcode version: 15.5
- iOS version: 17.2
- Maps SDK Version: 11.1.0 (tried 11.0.0 & beta 11.2.0 as well

I'm porting existing code in SwiftUI from Maps SDK v10 to v11.  Everything is working great, but I have run into one issue.  There's a noticeable latency with the onMapTapGesture.  Problem doesn't exist in v10, nor in my testing with an old school swift implementation on MapBox v11.  I created a test application to confirm, which consists of just the code below.  

```
import SwiftUI
@_spi(Experimental) import MapboxMaps

struct MapView: View {
    
    @State var touchPoint:CLLocationCoordinate2D? = nil
    let coords = CLLocationCoordinate2D(latitude: 31, longitude: -82)

    var body: some View {
        MapReader { proxy in
            Map(initialViewport: .camera(center: coords, zoom: 8)) {
                if let point = touchPoint {
                    CircleAnnotation(centerCoordinate: point)
                        .circleRadius(20)
                        .circleColor(StyleColor(.white))
                        .circleOpacity(0.75)
                }
            }
            .mapStyle(.standard)
            .onMapTapGesture { context in
                touchPoint = context.coordinate
            }
            .ignoresSafeArea()
        }
    }
}
```

Interestingly, the latency is resolved when I add a gesture recognizer to the MapReader like so:
```
var body: some View {
        let _ = print("rndr:", Date.now.timeIntervalSince1970)
        MapReader { proxy in
            Map(initialViewport: .camera(center: coords, zoom: 8)) {
                if let point = touchPoint {
                    CircleAnnotation(centerCoordinate: point)
                        .circleRadius(20)
                        .circleColor(StyleColor(.white))
                        .circleOpacity(0.75)
                }
            }
            .mapStyle(.standard)
            .onMapTapGesture { context in
                let _ = print("tap:", Date.now.timeIntervalSince1970)
                touchPoint = context.coordinate
            }
            .ignoresSafeArea()
        }
        .gesture(
            TapGesture()
                .onEnded { _ in
                    print("view-tap:", Date.now.timeIntervalSince1970)
                }
        )
    }
```

Not exactly sure what's going on here, but thought I'd bring it to y'alls attention.

**Comment by persidskiy** [comment]
@Tapestes Hi, this behavior is expected. It happens because the single tap gesture recognizer [awaits](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Gestures/GestureManager.swift#L188) the double-tap gesture recognizer to fail, so tap and zoom gestures don't conflict.

If we disable this, then those gestures will conflict. For example, in the video below I add an annotation in response to `onMapTapGesture`. The annotation is added even if I do double-tap quickzoom gesture

https://github.com/mapbox/mapbox-maps-ios/assets/1527181/b0ea4311-5fa9-4973-899d-06e17220264f

In v10 the behavior for `singleTapGesture` [was the same](https://github.com/mapbox/mapbox-maps-ios/blob/lts/v10/Sources/MapboxMaps/Gestures/GestureManager.swift#L156), but it wasn't widely used. In v11 we use it as single tap gesture trigger in the new [gesture system](https://docs.mapbox.com/ios/maps/api/11.2.0-beta.1/documentation/mapboxmaps/map-content-gestures-user-guide/).

**Comment by Tapestes** [comment]
@persidskiy, got it.  Thanks for the explanation.

**Comment by Tapestes** [comment]
@persidskiy, got it. Thanks for the explanation.
