### ISSUE TITLE
Mapbox Maps SDK crashes with Symbol layer!

### ISSUE THREAD

**Issue by OffsureDev** [mapbox/mapbox-maps-ios#2167]
## Environment

- Xcode version: 15.0.1
- iOS version: 16
- Devices affected: All
- Maps SDK Version: 10.16.3

## Observed behavior and steps to reproduce

Add multiple(more than 400) annotations with the Symbol layer on Map and Zoom in on the annotation's location. 

## Expected behavior

 It should present multiple annotations with a symbol layer without crashing. 

![Screenshot 2024-04-10 at 3 40 22 PM](https://github.com/mapbox/mapbox-maps-ios/assets/132354035/ce0d4ded-d93e-4f64-8750-21ad2e1dd929)
![Screenshot 2024-04-10 at 4 45 33 PM](https://github.com/mapbox/mapbox-maps-ios/assets/132354035/426d78c6-d823-457d-8f37-f5f745a0797c)
![Screenshot 2024-04-11 at 3 20 47 PM](https://github.com/mapbox/mapbox-maps-ios/assets/132354035/dfa20a7e-7140-45d7-b99d-a48f238eba81)

**Comment by pjleonard37** [comment]
Hi @OffsureDev -- 

Thanks for sharing this report. More information is needed to identify the root cause of this crash you are seeing. To more easily share this info, please reach out to our Support team using the contact form linked at the bottom of [this page](https://www.mapbox.com/support). They can assist you in diagnosing the problem.

As your investigation will continue there I'm going to close out this issue.
