### ISSUE TITLE
ITMS-91056

### ISSUE THREAD

**Issue by lavkushry1** [mapbox/mapbox-maps-ios#2181]
ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/MapboxCommon.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

in my project I am Using Dependency of
flutter_mapbox_navigation: ^0.2.2

but official Dependency is 
mapbox_maps_flutter: ^2.0.0-beta.1

is this raising the error or anything Else

**Comment by maios** [comment]
Hi @lavkushry1, I am a little bit confused, the dependency you posted above [flutter_mapbox_navigation](https://pub.dev/packages/flutter_mapbox_navigation/versions/0.2.2) is published 7 months ago, while our [MapboxMaps Flutter plugin v2.0.0-beta.1](https://pub.dev/packages/mapbox_maps_flutter/versions/2.0.0-beta.1) is published 6 days ago.
Since MapboxMaps Flutter plugin v1.0.0 we have updated our MapboxMaps SDK dependency to v11.3.0 which contains the fix for this invalid privacy manifest issue. So can you check that you really are using our latest Flutter plugin version?
