### ISSUE TITLE
Setting iconRotate dynamically has no effect

### ISSUE THREAD

**Issue by akirmse** [mapbox/mapbox-maps-ios#599]
In 10.0.0-rc.6, setting ```PointAnnotation.iconRotate``` after the annotation has been added to a ```PointAnnotationManager``` has no effect.  I'd like to dynamically set the rotation of an annotation.  It's far too expensive to remove and re-add the annotation to do this.

In 10.0.0-beta.19, it looks like there was an ```updateAnnotation``` method that presumably allowed dynamic updates:

https://docs.mapbox.com/ios/maps/api/10.0.0-beta.19/Classes/AnnotationManager.html#/s:10MapboxMaps17AnnotationManagerC06updateC0yyAA0C0_pKF

On Android, there is a similar ```PointAnntotationManager.update``` function that I am successfully using to update the rotation dynamically:

https://docs.mapbox.com/android/maps/api/10.0.0-rc.6/-mapbox%20-maps%20-android/com.mapbox.maps.plugin.annotation.generated/-point-annotation-manager/#com.mapbox.maps.plugin.annotation/AnnotationManagerImpl/update/#com.mapbox.maps.plugin.annotation.generated.PointAnnotation/PointingToDeclaration/

**Comment by akirmse** [comment]
@macdrevx I have several hundred annotations, one of which I want to rotate at high frequency along with the device's heading.  In the Mapbox Android SDK (and presumably in beta19?), I call ```PointAnnotationManager.update``` and performance is reasonable.  How do I do this in rc6?

**Comment by macdrevx** [comment]
The performance characteristics of the update method on android method you mention are similar to on iOS — even though the interface allows you to pass a single annotation to update, under the hood, all the annotations managed by that manager get retransmitted to the renderer. This is something we're interested in optimizing in the future.

For now, if you're experiencing a performance bottleneck, one option to consider would be to create a separate annotation manager for the annotation that is updated frequently. Doing so will minimize the work that needs to be done when you update that annotation. Note that there will be a layering impact since each annotation manager gets its own layer, so you'll have to decide whether you want the frequently-updating annotation to be above or below the other ones.

**Comment by akirmse** [comment]
Thanks, I'll give that a try.  Should it be documented that updating properties after creation has no effect?  Perhaps it should even be disallowed.

I'm adding Mapbox to a substantial app that already uses the Google Maps SDK.  In the Google SDK, it is easier to get good performance: all properties are dynamic, and there isn't a need to batch up changes.

**Comment by macdrevx** [comment]
cc: @nishant-karajgikar @tobrun
