### ISSUE TITLE
Incremental Compilation does not work in xCode 13 with new version of maps 10.0 and Navigation 2.0

### ISSUE THREAD

**Issue by jcfrk101** [mapbox/mapbox-maps-ios#810]
## Environment

- Xcode version: 13+
- iOS version: 15
- Devices affected: iPhones
- Maps SDK Version: 10.0 and Navigation 2.0

## Observed behavior and steps to reproduce
Compilation takes much longer than is should

I see the following output in the build logs for the mapbox and navigation SDK's

Set ENABLE_PREVIEWS=NO because SWIFT_OPTIMIZATION_LEVEL=-Owholemodule, expected -Onone

remark: Incremental compilation has been disabled: it is not compatible with whole module optimization

**Comment by ZiZasaurus** [comment]
Could you provide the following additional information: 

- How long does compilation take?
- How are you integrating the SDKs (SPM? CocoaPods?) 
- Do you see this issue with the Maps SDK alone? 

Additionally, if you could provide more context from your build logs that would be helpful as well.

**Comment by ZiZasaurus** [comment]
@jcfrk101 Thank you for this information. For #3, yes, are you using the Maps SDK along with the Navigation SDK or by itself?

**Comment by jcfrk101** [comment]
I am using them together.

**Comment by ZiZasaurus** [comment]
If you are seeing this issue with just the Maps SDK, could you share how long the compilation takes and more information about your macOS version? If you are only seeing this issue when using the Maps SDK with the Navigation SDK, could you open a ticket in (link to nav repo). It looks like SWIFT_OPTIMIZATION_LEVEL=-Owholemodule is set there.

**Comment by jcfrk101** [comment]
I'm not sure which project is doing this, but here is a picture of the MapBox Maps 10.0 package installed via SPM. As you can see the project file has whole module enabled.[](ur
![Screen Shot 2021-11-18 at 7 23 35 PM](https://user-images.githubusercontent.com/5083151/142535221-72afc65e-d85a-4160-9238-7035ec409042.png)
l)

**Comment by ZiZasaurus** [comment]
@jcfrk101  the compilation time heavily depends on your overall configuration. Additionally, because you're using SPM, optimization level is determined by settings in your project, or possibly some defaults in SPM, not by settings in our Swift Package. The config you highlighted in your most recent comment is only relevant when we run unit tests and isn't used for anything else.

Are you certain Maps/Nav is the culprit? Looking into the Package.swift files for both [Maps](https://github.com/mapbox/mapbox-maps-ios/blob/main/Package.swift) and [Nav](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Package.swift) SDKs, neither mentions optimization level.

**Comment by ZiZasaurus** [comment]
@jcfrk101 Closing this ticket out but please feel free to reopen if you have additional questions.
