### ISSUE TITLE
Globe Example incorrect display on iPhone6s plus

### ISSUE THREAD

**Issue by lishuo0710** [mapbox/mapbox-maps-ios#895]
## Environment

- Xcode version:12
- iOS version:13.6.1
- Devices affected:iPhone6s plus
- Maps SDK Version: 10.2.0. rc1

Globe Example incorrect display as below
![20211203162359](https://user-images.githubusercontent.com/25873946/144569790-abf349c4-58ca-4e4c-9af2-c86a8a9089bd.jpg)
.

**Comment by macdrevx** [comment]
cc: @astojilj @mpulkki-mapbox

**Comment by macdrevx** [comment]
also @endanke in case this is an issue with our example

**Comment by endanke** [comment]
@macdrevx I have a strong feeling that this is caused by the pixel ratio of the device. (I saw a similar issue previously when moved the surface to an external display with different density.) 
I'll investigate this further after the long weekend and try to prepare a fix!

**Comment by endanke** [comment]
I did some further investigation and indeed the pixel ratio is the issue: currently we render the atmosphere behind the globe using the size and pixel ratio of the screen. (It's planned to be refactored later on to make it independent of those.)
In case the device is using a different screen scaling than the native one, then the atmosphere will have this alignment issue. I think if we use `UIScreen.mainScreen.nativeScale` instead of `UIScreen.mainScreen.scale` as a default pixel ratio in `MapboxCoreMaps.MapOptions` then it should solve the issue. 

I tested this using the Display Zoom feature on an iPhone 11 Pro, which also changes the scaling:

Using `UIScreen.mainScreen.scale` in options:

![IMG_8837](https://user-images.githubusercontent.com/2576246/145038425-1170b1aa-c972-4195-adec-33568401b3dd.PNG)

Using `UIScreen.mainScreen.nativeScale` in options:

![IMG_8838](https://user-images.githubusercontent.com/2576246/145038418-4e12ceb2-5db1-48f8-8194-13b516a37e78.PNG)

**Comment by endanke** [comment]
Created a PR to change the default pixel ratio: https://github.com/mapbox/mapbox-maps-ios/pull/906
Also opened an issue to make the atmosphere shader independent from this value, which would prevent other issues in the future (in case a customer wants to explicitly use a different pixel ratio): https://github.com/mapbox/mapbox-3d-team/issues/71
